// lib/src/tax/tax_calculator.dart
//
// Dart wrapper for the Rust tax-core library via flutter_rust_bridge.
// Monetary values match the backend's DECIMAL(20, 6) exactly.
//
// Setup:
//  dependencies:
//      flutter_rust_bridge: ^2.0.0
//      decimal: ^2.3.3
//
//  dev_dependencies:
//      flutter_rust_bridge_codegen: ^2.0.0
//
// After adding deps, run:
//   flutter_rust_bridge_codegen generate
//
// Usage:
//  final result = await TaxCalculator.calculate(
//     price: Decimal.parse('99.990000'),
//     region: Region.eu,
//     category: Category.digital
// );
// print(result.ratePercent);   // Decimal 20.000000
// print(result.priceAfterTax); // Decimal 119.988000
// print(result.rateDisplay);   // "20.000000 %"

import 'package:decimal/decimal.dart';
// Generated by flutter_rust_bridge_codegen - do not edit directly.
import 'package:your_app/src/rust/api/tax.dart' as _bridge;
export 'package:your_app/src/rust/api/tax.dart' show Region, Category;

// ------
// Result - all monetary fields are Decimal (maps to DECIMAL(20, 6))
// ------

class TaxResult {
    /// Pre-tax price as DECIMAL(20,6).
    final Decimal priceBeforeTax;

    /// Effective rate as a fraction, e.g. Decimal.parse('0.200000').
    final Decimal rate;

    /// Rate as a percentage, e.g. Decimal.parse('20.000000').
    final Decimal ratePercent;

    /// Tax amount as DECIMAL(20, 6).
    final Decimal taxAmount;

    /// Total price including tax as DECIMAL(20,6).
    final Decimal priceAfterTax;

    /// ISO currency hint, e.g. "EUR".
    final String currency;

    final String regionDisplay;
    final String categoryDisplay;

    const TaxResult._({
        required this.priceBeforeTax,
        required this.rate,
        required this.ratePercent,
        required this.taxAmount,
        required this.priceAfterTax,
        required this.currency,
        required this.regionDisplay,
        required this.categoryDisplay
    });

    /// Human-readable rate-string, e.g. "20.000000 %"
    String get rateDisplay => '$ratePercent %';

    @override
    String toString() =>
        'TaxResult(before: $priceBeforeTax, tax: $taxAmount ($rateDisplay),'
        'after: $priceAfterTax $currency)';
}

// ------
// Exception
// ------

class TaxCalculatorException implements Exception {
    final String message;
    const TaxCalculatorException(this.message);

    @override
    String toString() => 'TaxCalculatorException: $message';
}

// ------
// Calculator
// ------

class TaxCalculator {
    TaxCalculator._();

    /// Calculate tax for a product.
    ///
    /// [price]        Pre-tax price as [Decimal] (matches DECIMAL(20, 6)).
    ///                e.g `Decimal.parse('99.990000')`
    /// [region]       Tax region.
    /// [category]     Product category.
    /// [customRate]   Override rate as a [Decimal] fraction, e.g.
    ///                `Decimal.parse('0.075000')` for 7.5%.
    ///                Pass `null` to use the region/category default.
    ///
    /// Throws [TaxCalculatorException] on invalid input.
    static Future<TaxResult> calculate({
        required Decimal price,
        Region region = Region.us,
        Category category = Category.general,
        Decimal? customRate,
    }) async {
        try {
            // Pass prices as fixed-point strings - The rust side parses them
            // as DECIMAL(20,6) without any floating-point involvement.
            final raw = await _bridge.calculateTax(
                price:      _toDecimalString(price),
                region:     region,
                category:   category,
                customRate:  customRate != null ? _toDecimalString(customRate) : '',
            );

            return TaxResult._(
                priceBeforeTax:   Decimal.parse(raw.priceBeforeTax),
                rate:             Decimal.parse(raw.rate),
                ratePercent:      Decimal.parse(raw.ratePercent),
                taxAmount:        Decimal.parse(raw.taxAmount),
                priceAfterTax:    Decimal.parse(raw.priceAfterTax),
                currency:         raw.currency,
                regionDisplay:    raw.regionDisplay,
                categoryDisplay:  raw.categoryDisplay
            );
        } on Exception catch (e) {
            throw TaxCalculatorException(e.toString());
        }
    }

    /// Get the effective rate for a region+category as a [Decimal] fraction.
    /// e.g `Decimal.parse('0.200000')` for EU/Digital.
    static Future<Decimal> effectiveRate(Region region, Category category) async {
        final rateStr = await _bridge.getEffectiveRate(
            region: region,
            category: category,
        );
        return Decimal.parse(rateStr);
    }

    /// Convenience: effective rate as a percentage Decimal.
    static Future<Decimal> effectiveRatePercent(
        Region region, Category category
    ) async {
        final rate = await effectiveRate(region, category);
        return rate * Decimal.fromInt(100);
    }

    // Serialize a Decimal to a Decimal(20,6) string for the Rust boundary.
    // Always 6 decimal places, no scientific notation.
    static String _toDecimalString(Decimal d) {
        // decimal package: toStringAsFixed gives the right format
        return d.toStringAsFixed(6);
    }
}

// ======
// Example Flutter widge
// ======

/*
import 'package:decimal/decimal.dart';
import 'package:flutter/material.dart';
import 'tax_calculator.dart';

class ProductPriceTile extends StatelessWidget {
    final String name;
    final Decimal price;
    final Region region;
    final Category category;

    const ProductPriceTile({
        super.key,
        required this.name,
        required this.price,
        required this.region,
        required this.category,
    });

    @override
    Widget build(BuildContext context) {
        return FutureBuilder<TaxResult>(
            future: TaxCalculator.calculate(
                price: price,
                region: region,
                category: category,
            ),
            builder: (context, snapshot) {
                if (snapshot.hasError) {
                    return Text('Tax error: ${snapshot.error}',
                        style: const TextStyle(color: Colors.red)
                    );
                }
                if (!snapshot.hasData) {
                    return const CircularProgressIndicator();
                }
                final t = snapshot.data!;
                return ListTile(
                    title: Text(name),
                    subtitle: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                            Text('${t.currency} ${t.priceBeforeTax.toStringAsFixed(2)} (before tax)'),
                            Text('Tax ${t.rateDisplay}: ${t.taxAmount.toStringAsFixed(2)}'),
                            Text(
                                'Total: ${t.currency} ${t.priceAfterTax.toStringAsFixed(2)}',
                                style: const TextStyle(fontWeight: FontWeight.bold),
                            ),
                        ]
                    )
                )
            }
        )
    }
}

// Parsing a price from your API response:
//
// final json = await api.getProduct(id);
// final price = Decimal.parse(json['price']); // "99.990000" -> exact Decimal
// final result = await TaxCalculator.calculate(price: price, region: Region.eu);
*/
